:data-uri:
:toc: left
:markup-in-source: +verbatim,+quotes,+specialcharacters
:source-highlighter: rouge
:icons: font
:stylesdir: stylesheets
:stylesheet: colony.css

= AMQ Online

AMQ Online is a solution (Operator) to manage multiple components to provide the over all functionality of running self-service (Messaging as a Service) messaging platform on OpenShift.

In this series i will explorer AMQ Online from basic concepts to multi-cluster deployments and multi-cluster connectors.

:sectnums:

== Understand AMQ Online
Introduction to AMQ Online components and basic understanding of important concepts and features.

link:understand[Understand AMQ Online]

== Building A Java Sample using camel routes
A quickstart to demonstrate how to connect using Camel routes (Spring-Boot based application) to an AMQ Online SaaS self-service messaging.

There are 2 usecase which will explorer

 * Publisher Subscriber usecase (Multicast) built using Standard Address.
 * Point-to-point usecase (Anycast) built using Brokered Address

link:build_java[Building A Java Sample]

= AMQ Online Multi-cluster deployment

A demo application using Ansible playbooks that deploy AMQ online on top of OpenShift deployed in two data centers, and configure
AMQ Online connectors & Forwarders for communication between AMQ online deployed on separate clusters.

link:multicluster_deploy[AMQ Online Multi-cluster deployment]
